### ISSUE TITLE
Invalid static compression directory

### ISSUE THREAD

**Issue by sneal** [cloudfoundry-incubator/hwc#7]
The following warning is observed in the Windows Application event log when an hwc process is started:

```
The directory specified for caching compressed content C:\Users\vagrant\tmp\IIS Temporary Compressed Files\AppPool8023 is invalid.  Static compression is being disabled.
```

This definitely happens locally outside Cloud Foundry, but I'm pretty certain I've seen this warning on a Windows cell before.

**Comment by crawsible** [comment]
Thanks @sneal; we'll investigate.

**Comment by sunjayBhatia** [comment]
Saw this again in a `windows2012R2` cell:

![screen shot 2018-01-16 at 1 44 42 pm](https://user-images.githubusercontent.com/5337253/35006071-8d6f347c-fac3-11e7-85b4-231e7d1a5363.png)

All of those warnings are the static compression error
